/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DjSNq0jNh9p
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { signIn } from "@/lib/auth"

export function LogIn() {
  return (
    <div
      className="relative flex items-center justify-center min-h-screen bg-cover bg-center"
      style={{ backgroundImage: 'url("https://images.unsplash.com/photo-1666427620472-5d4536c2f557")' }}
    >
      <div className="absolute inset-0 bg-black opacity-50" />
      <div className="relative z-10 w-full max-w-md p-8 bg-black bg-opacity-75 rounded-md">
        <h1 className="text-3xl font-bold text-white">Sign In</h1>
        <form className="space-y-4" action={async () => {
          "use server"
          await signIn("keycloak", { callbackUrl: "/" })
        }}>
          <Button
            type="submit"
            className="w-full px-4 py-2 font-medium text-white bg-red-600 rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500"
          >
            Sign In
          </Button>
        </form>
        <p className="mt-4 text-sm text-gray-300">
          Don't have an account?{" "}
          <Link href="/signup" className="text-white hover:underline" prefetch={false}>
            Sign up now
          </Link>
          .
        </p>
      </div>
    </div>
  )
}
