version: '3'

tasks:
  build:
    cmds:
      - go build -o identityaccess ./identityaccess/main.go
    sources:
      - ./**/*.go
    generates:
      - identityaccess
    method: timestamp
  
  run:
    cmds:
      - ./identityaccess
    depends:
      - build

  clean:
    cmds:
      - rm -f identityaccess
