version: "3"

tasks:
  build:
    cmds:
      - go build -o idapi ./identityaccess/main.go
    sources:
      - ./**/*.go
    generates:
      - identityaccess
    method: timestamp

  run:
    cmds:
      - ./identityaccess
    depends:
      - build

  clean:
    cmds:
      - rm -f identityaccess

  dbmigration:
    cmds:
      - go run ./dbmigration/main.go
